---
title: "Figures"
author: "Huaying Qiu"
date: "2023-10-11"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r}

library(tidyverse)
library(ComplexHeatmap)

```


```{r}

celltype_color <- c('Tumor' = '#E41A1C', 'DC' = '#377EB8', 'B' = '#F781BF', 'CD4' = '#4DAF4A', 'CD8' = '#984EA3',
                    'M2' = '#F7C173', 'NK' = '#FFFF33', 'Endothelial' = '#A65628', 'M1' = '#00FFFF', 'Neutrophil' = '#F6CEC1',
                    'Treg' = '#BEBADA', 'Cytotoxic CD4' = '#253D24', 'Cytotoxic CD8' = '#FF7F00')

celltype_color[sort(names(celltype_color))]


hodgkin_annotated <- read_csv('~/Hodgkin_github/data/hodgkin_DFCI.csv')

hodgkin_annotated <- hodgkin_annotated %>% 
  mutate(ebv_status = factor(ebv_status, levels = c('Positive', 'Negative')))

```

## Figure 2

### Figure 2A

```{r}

# Get list of markers

markers <- c('CD11c', 'CD14', 'CD15', 'CD153 (CD30L)', 'CD16', 'CD163', 'CD20', 'CD3', 'CD30', 'CD4', 'CD56', 'CD57', 'CD68', 'CD8', 'FoxP3', 'GATA3', 'Granzyme B', 'Pax-5')

hodgkin_heatmap_df <- hodgkin_annotated %>% 
  dplyr::filter(ebv_status != 'control') %>% 
  dplyr::select(Annotation, all_of(markers))

mean_df <- hodgkin_heatmap_df %>% 
  pivot_longer(cols = -Annotation, names_to = 'marker', values_to = 'value') %>% 
  group_by(marker, Annotation) %>% 
  summarise(mu = mean(value))


pop_mean_df <- hodgkin_heatmap_df %>% 
  pivot_longer(cols = -Annotation, names_to = 'marker') %>% 
  group_by(marker) %>% 
  summarise(pop_mean = mean(value),
            pop_sd = sd(value))

mean_df <- mean_df %>% 
  ungroup() %>% 
  mutate(pop_mean = pop_mean_df$pop_mean[match(mean_df$marker, pop_mean_df$marker)],
         pop_sd = pop_mean_df$pop_sd[match(mean_df$marker, pop_mean_df$marker)]) %>% 
  mutate(z_new = (mu - pop_mean)/pop_sd)

heatmap_df <- mean_df %>% 
  dplyr::select(marker, z_new, Annotation) %>% 
  pivot_wider(names_from = 'marker', values_from = 'z_new')

heatmap_mat <- t(as.matrix(heatmap_df[,2:19]))

colnames(heatmap_mat) <- heatmap_df$Annotation

library(circlize)
col_fun = colorRamp2(c(-1, 0, 1), c('#4575b4', "white", '#d73027'))

bar_vec <- hodgkin_annotated %>% 
  group_by(Annotation) %>% 
  dplyr::count() %>% 
  mutate(log_n = log10(n))

column_ha <- HeatmapAnnotation(count = anno_barplot(bar_vec$n, border = FALSE, bar_width = 0.9,
                                                    gp = gpar(col = 'black', fill = rep(celltype_color[sort(names(celltype_color))], 2)),
                                                    height = unit(3, 'cm')),
                               show_annotation_name = FALSE)

column_ha2 <- HeatmapAnnotation(celltype = sort(names(celltype_color)),
                                col = list(celltype = celltype_color), show_annotation_name = FALSE,
                                gp = gpar(col = 'black', lwd = 2),
                                annotation_legend_param = list(title = 'Cell Type'))

fig2_h1 <- Heatmap(heatmap_mat, cluster_rows = FALSE, cluster_columns  = FALSE, col = col_fun, clustering_method_columns = 'complete',
        row_names_side = 'left', top_annotation = column_ha, column_names_gp = grid::gpar(fontsize = 12),
  row_names_gp = grid::gpar(fontsize = 12), rect_gp = gpar(col = "black", lwd = 2), show_column_names = FALSE, name = 'Z Score',
  heatmap_legend_param = list(border = 'black'))






```

```{r}

markers <- c('B2-Microglobulin', 'CD45RA', 'CD45RO', 'CXCR5', 'HLA-DR', 'HLA1', 'Ki-67', 'Lag3', 'PD-1', 'PD-L1','Tox')

hodgkin_heatmap_df <- hodgkin_annotated %>% 
  dplyr::select(Annotation, all_of(markers))

mean_df <- hodgkin_heatmap_df %>% 
  pivot_longer(cols = -Annotation, names_to = 'marker', values_to = 'value') %>% 
  group_by(marker, Annotation) %>% 
  summarise(mu = mean(value))


pop_mean_df <- hodgkin_heatmap_df %>% 
  pivot_longer(cols = -Annotation, names_to = 'marker') %>% 
  group_by(marker) %>% 
  summarise(pop_mean = mean(value),
            pop_sd = sd(value))

mean_df <- mean_df %>% 
  ungroup() %>% 
  mutate(pop_mean = pop_mean_df$pop_mean[match(mean_df$marker, pop_mean_df$marker)],
         pop_sd = pop_mean_df$pop_sd[match(mean_df$marker, pop_mean_df$marker)]) %>% 
  mutate(z_new = (mu - pop_mean)/pop_sd)

heatmap_df <- mean_df %>% 
  dplyr::select(marker, z_new, Annotation) %>% 
  pivot_wider(names_from = 'marker', values_from = 'z_new')

heatmap_mat <- t(as.matrix(heatmap_df[,2:12]))

colnames(heatmap_mat) <- heatmap_df$Annotation

library(circlize)
col_fun = colorRamp2(c(-1, 0, 1), c('#4575b4', "white", '#d73027'))

bar_vec <- hodgkin_annotated %>% 
  group_by(Annotation) %>% 
  dplyr::count()

column_ha <- HeatmapAnnotation(count = anno_barplot(bar_vec$n))

column_ha2 <- HeatmapAnnotation(celltype = sort(names(celltype_color)),
                                col = list(celltype = celltype_color), show_annotation_name = FALSE,
                                gp = gpar(col = 'black', lwd = 2),
                                annotation_legend_param = list(title = 'Cell Type'))

fig2_h2 <- Heatmap(heatmap_mat, cluster_rows = FALSE, cluster_columns  = FALSE, col = col_fun, clustering_method_columns = 'complete',
        row_names_side = 'left', column_names_gp = grid::gpar(fontsize = 12),
  row_names_gp = grid::gpar(fontsize = 12), rect_gp = gpar(col = "black", lwd = 2),
  bottom_annotation = column_ha2, name = 'Z Score', heatmap_legend_param = list(border = 'black'))

```


```{r}

pdf('~/hodgkinebvmibi/paper_figures/figure2/figure2A.pdf', width = 10, height = 15)

fig2_heatmap_list <- fig2_h1 %v% fig2_h2

draw(fig2_heatmap_list, ht_gap = unit(0.1, 'cm'))

dev.off()

```



```{r}

library(raster)

seg_list <- list.files('~/hodgkinebvmibi/20220823_cHL-DFCI_Production_M060/', full.names = TRUE, recursive = TRUE, pattern = 'segmentationMap.tif')

# Exchange position of masks of the two LN

seg_list <- replace(seg_list, c(31,32), seg_list[c(32,31)])

# Read in segmentation mask

mask_list <- map(seg_list, function(x){
  as.matrix(raster(x))
})

# outline_list <- list.files('~/hodgkinebvmibi/20220823_cHL-DFCI_Production_M060/', full.names = TRUE, recursive = TRUE, pattern = 'segmentationMask_boundary.tif')
# 
# outline_list <- replace(outline_list, c(31,32), outline_list[c(32,31)])
# 
# outline <- map(outline_list, function(x){
#   as.matrix(raster(x))
# })


```


```{r}

new_annotation <- hodgkin_annotated %>% 
  dplyr::filter(is.na(fov)) %>% 
  dplyr::select(pointNum, patientID, region, Annotation, cellLabel)

pointNum_ID_region_LUT <- new_annotation %>% 
  group_by(pointNum, patientID, region) %>% 
  dplyr::count() %>% 
  dplyr::select(-n)

celltype_plot <- function(point_num, seg_list, annotation, cell_label, mypalette, pointNumLUT, verbose = FALSE, out = FALSE, out_path = NULL, print_fig = FALSE){
  require(reshape2)
  require(purrr)
  require(ggplot2)
  require(dplyr)
  require(tidyr)
  # Get segmentation matrix
  seg_mat <- seg_list[[point_num - 2]]
  # Get segmentation outline
  #seg_outline <- outline[[point_num - 2]]
  # Get cell types for this point. Stored as a list
  cell_type <- as.list(unique(annotation))
  # Store cell label of each cell type in a list
  type_label_LUT <- map(cell_type, function(x){
    cell_label[annotation == x]
  })
  # Name list by cell type
  names(type_label_LUT) <- unique(annotation)
  # Reshape segmentation matrix and add a column called pixel type
  mat_long <- melt(seg_mat)
  mat_long <- mat_long %>% 
    mutate(pixel_type = rep(NA, nrow(mat_long)))
  # outline_long <- melt(seg_outline)
  # outline_long <- outline_long %>%
  # mutate(pixel = ifelse(value == 1, 'outline', NA))
  # Fill in pixel type by cell type
  for (i in 1:length(unique(annotation))){
    mat_long$pixel_type[mat_long$value %in% type_label_LUT[[i]]] <- unique(annotation)[i]
  }
  # Match cell type and color to make sure color is uniform across the board
  color <- mypalette$color[match(unique(annotation), mypalette$celltype)]
  # Match pointNum, patientID, and region
  plot_title <- paste0(pointNumLUT$patientID[pointNumLUT$pointNum == point_num], '_', pointNumLUT$region[pointNumLUT$pointNum == point_num])
  # Plot 
  p <- ggplot()+
    #geom_tile(data = outline_long, aes(x = Var2, y = -Var1, fill = as.factor(pixel))) + 
    #scale_fill_manual(values = c('#FFFFFF'), na.value = 'white', na.translate = FALSE) + 
    geom_raster(data = mat_long, aes(x = Var2, y = -Var1, fill = pixel_type)) + 
    scale_fill_manual('Cell Types', breaks = unique(annotation), values = color, na.value = 'white', drop = FALSE) +
    #scale_fill_brewer(palette = 'Set3', direction = -1, na.value = 'white', breaks = unique(annotation)) + 
    #labs(title = paste0(plot_title), fill = 'Cell Types') + 
    theme(axis.title = element_blank(),
          axis.ticks = element_blank(),
          axis.line = element_blank(),
          axis.text = element_blank(),
          panel.background = element_blank(),
          panel.grid = element_blank(),
          legend.position = 'none')
  # Show plot
  if (verbose){
    cat('Plot for PointNum ', point_num, ' completed. \n')
  }
  if (out){
    ggsave(filename = paste0(out_path, plot_title, '.png'), plot = p, device = 'png', height = 9, width = 9, units = 'in', dpi = 320)
    #legend_plot <- cowplot::get_legend(p)
    #ggsave(filename = paste0(out_path, 'legend.pdf'), plot = legend_plot, device = 'pdf', dpi = 320)
  }
  if (print_fig){
    print(p)
  }
}

```

```{r}

library(foreach)

mypalette <- data.frame(celltype = c('Tumor', 'Other', 'DC', 'B', 'CD4', 'CD8', 'M2', 'NK', 'Endothelial', 'M1', 'Neutrophil', 'Treg', 'Cytotoxic CD4', 'Cytotoxic CD8'),
                        color = c('#E41A1C', '#999999', '#377EB8', '#F781BF', '#4DAF4A', '#984EA3', '#f7c173', '#FFFF33', '#A65628', '#00FFFF', '#f6cec1', '#BEBADA', '#253d24', '#FF7F00'))

cl <- parallel::makeCluster(20)
doParallel::registerDoParallel(cl)

foreach (i = unique(new_annotation$pointNum)) %dopar% {
  celltype_plot(i, mask_list, new_annotation$Annotation[new_annotation$pointNum == i], new_annotation$cellLabel[new_annotation$pointNum == i], mypalette = mypalette, pointNumLUT = pointNum_ID_region_LUT, verbose = TRUE, out = TRUE, out_path = '~/hodgkinebvmibi/paper_figures/pheno_map_no_legend/')
}

parallel::stopCluster(cl)

```

## SingleFOV phenotype Map


```{r}

library(raster)

seg_list <- list.files('~/hodgkinebvmibi/20220823_cHL-DFCI_Production_singleFOV_M060/', full.names = TRUE, recursive = TRUE, pattern = 'segmentationMap.tif')

# Read in segmentation mask

mask_list <- map(seg_list, function(x){
  as.matrix(raster(x))
})

```


```{r}

new_annotation <- hodgkin_annotation_with_marker %>% 
  dplyr::filter(!is.na(fov)) %>% 
  dplyr::select(pointNum, patientID, fov, Annotation, cellLabel)

pointNum_ID_fov_LUT <- new_annotation %>% 
  group_by(pointNum, patientID, fov) %>% 
  dplyr::count() %>% 
  dplyr::select(-n)

celltype_plot <- function(point_num, seg_list, annotation, cell_label, mypalette, pointNumLUT, verbose = FALSE, out = FALSE, out_path = NULL, print_fig = FALSE){
  require(reshape2)
  require(purrr)
  require(ggplot2)
  require(dplyr)
  require(tidyr)
  # Get segmentation matrix
  seg_mat <- seg_list[[point_num - 34]]
  # Get cell types for this point. Stored as a list
  cell_type <- as.list(unique(annotation))
  # Store cell label of each cell type in a list
  type_label_LUT <- map(cell_type, function(x){
    cell_label[annotation == x]
  })
  # Name list by cell type
  names(type_label_LUT) <- unique(annotation)
  # Reshape segmentation matrix and add a column called pixel type
  mat_long <- melt(seg_mat)
  mat_long <- mat_long %>% 
    mutate(pixel_type = rep(NA, nrow(mat_long)))
  # Fill in pixel type by cell type
  for (i in 1:length(unique(annotation))){
    mat_long$pixel_type[mat_long$value %in% type_label_LUT[[i]]] <- unique(annotation)[i]
  }
  # Match cell type and color to make sure color is uniform across the board
  color <- mypalette$color[match(unique(annotation), mypalette$celltype)]
  # Match pointNum, patientID, and region
  plot_title <- paste0(pointNumLUT$patientID[pointNumLUT$pointNum == point_num], '_', pointNumLUT$fov[pointNumLUT$pointNum == point_num])
  # Plot 
  p <- ggplot()+
    geom_raster(data = mat_long, aes(x = Var2, y = -Var1, fill = pixel_type)) + 
    scale_fill_manual('Cell Types', breaks = unique(annotation), values = color, na.value = 'white', drop = FALSE) +
    #scale_fill_brewer(palette = 'Set3', direction = -1, na.value = 'white', breaks = unique(annotation)) + 
    #labs(title = paste0(plot_title), fill = 'Cell Types') + 
    theme(axis.title = element_blank(),
          axis.ticks = element_blank(),
          axis.line = element_blank(),
          axis.text = element_blank(),
          panel.background = element_blank(),
          panel.grid = element_blank(),
          legend.position = 'none')
  # Show plot
  if (verbose){
    cat('Plot for PointNum ', point_num, ' completed. \n')
  }
  if (out){
    ggsave(filename = paste0(out_path, plot_title, '.png'), plot = p, device = 'png', height = 9, width = 9, units = 'in', dpi = 320)
    #legend_plot <- cowplot::get_legend(p)
    #ggsave(filename = paste0(out_path, 'legend.pdf'), plot = legend_plot, device = 'pdf', dpi = 320)
  }
  if (print_fig){
    print(p)
  }
}

```

```{r}

library(foreach)

mypalette <- data.frame(celltype = c('Tumor', 'Other', 'DC', 'B', 'CD4', 'CD8', 'M2', 'NK', 'Endothelial', 'M1', 'Neutrophil', 'Treg', 'Cytotoxic CD4', 'Cytotoxic CD8'),
                        color = c('#E41A1C', '#999999', '#377EB8', '#F781BF', '#4DAF4A', '#984EA3', '#f7c173', '#FFFF33', '#A65628', '#00FFFF', '#f6cec1', '#BEBADA', '#253d24', '#FF7F00'))

cl <- parallel::makeCluster(8)
doParallel::registerDoParallel(cl)

foreach (i = unique(new_annotation$pointNum)) %dopar% {
  celltype_plot(i, mask_list, new_annotation$Annotation[new_annotation$pointNum == i], new_annotation$cellLabel[new_annotation$pointNum == i], mypalette = mypalette, pointNumLUT = pointNum_ID_fov_LUT, verbose = TRUE, out = TRUE, out_path = '~/hodgkinebvmibi/paper_figures/singleFOV_pheno/')
}

parallel::stopCluster(cl)

```



### Figure 2B

```{r}

library(tidytext)

p <- hodgkin_annotated %>% 
  filter(ebv_status != 'control') %>% 
  mutate(ebv_status = factor(ebv_status, levels = c('Positive', 'Negative'))) %>% 
  group_by(pointNum, Annotation, ebv_status) %>% 
  dplyr::count() %>%
  ungroup() %>% 
  group_by(pointNum, ebv_status) %>% 
  mutate(order_vec = ifelse(ebv_status == 'Positive', n[Annotation == 'CD8']/sum(n), n[Annotation == 'CD4']/sum(n))) %>% 
  mutate(Annotation = reorder_within(Annotation, -n, ebv_status)) %>% 
  ggplot(aes(x = reorder(as.factor(pointNum), -order_vec), y = n, fill = Annotation)) + 
  geom_col(position = 'fill') + 
  facet_grid(~ebv_status, scales = 'free_x', space = 'free') + 
  scale_fill_manual('Cell Types', values = c('Tumor___Positive' = '#E41A1C', 'Tumor___Negative' = '#E41A1C', 'DC___Positive' = '#377EB8', 'DC___Negative' = '#377EB8', 
                                             'B___Positive' = '#F781BF', 'B___Negative' = '#F781BF', 'CD4___Positive' = '#4DAF4A', 'CD4___Negative' = '#4DAF4A', 'CD8___Positive' = '#984EA3', 
                                             'CD8___Negative' = '#984EA3', 'M2___Positive' = '#f7c173', 'M2___Negative' = '#f7c173', 'NK___Positive' = '#FFFF33', 
                                             'NK___Negative' = '#FFFF33', 'Endothelial___Positive' = '#A65628', 
                                             'Endothelial___Negative' = '#A65628', 'M1___Positive' = '#00FFFF', 
                                             'M1___Negative' = '#00FFFF',
           'Neutrophil___Positive' = '#f6cec1', 'Neutrophil___Negative' = '#f6cec1', 'Treg___Positive' = '#BEBADA', 
           'Treg___Negative' = '#BEBADA', 'Cytotoxic CD4___Positive' = '#253d24', 
           'Cytotoxic CD4___Negative' = '#253d24', 'Cytotoxic CD8___Positive' = '#FF7F00', 'Cytotoxic CD8___Negative' = '#FF7F00'), na.value = 'white') + 
  theme_bw() + 
  theme(text = element_text(size = 15),
        legend.position = 'none',
        axis.text.x = element_text(angle = 90)) + 
  labs(x = 'FOV', y = 'Proportion')

ggsave('/mnt/nfs/home/huayingqiu/hodgkinebvmibi/paper_figures/cell_composition_combined_perFOV.pdf',p,dpi = 320)

```



### Figure 2C


```{r}

celltype_log2c <- hodgkin_annotated %>% 
  group_by(Annotation, ebv_status) %>% 
  dplyr::count() %>% 
  dplyr::filter(ebv_status != 'control') %>% 
  ungroup() %>% 
  group_by(ebv_status) %>% 
  mutate(total_n = sum(n)) %>% 
  ungroup() %>% 
  group_by(Annotation) %>% 
  mutate(diff = log2((lag(n)/lag(total_n)) / (n/total_n))) %>% 
  drop_na() %>% 
  ggplot(aes(x = reorder(Annotation, diff), y = diff, fill = Annotation)) +
  geom_col() + 
  geom_rect(aes(xmin = 0, ymin = 0, xmax = Inf, ymax = Inf), fill = '#D55E00', alpha = 0.02) + 
  geom_rect(aes(xmin = 0, ymin = -Inf, xmax = Inf, ymax = 0), fill = '#009E73', alpha = 0.02) + 
  #annotate('text', x = 2, y = 1.5, label = 'EBV+', size = 12) +
  #annotate('text', x = 13, y = -1, label = 'EBV-', size = 12) +
  labs(x = 'Cell Type', y = 'Log2 Fold Enrichment', title = 'Cell Type Enrichment (EBV+/EBV-)') + 
  scale_fill_manual('Cell Types', values = celltype_color, na.value = 'white') +
  theme_bw() + 
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5),
        legend.position = 'none',
        text = element_text(size = 12))
  
ggsave('/mnt/nfs/home/huayingqiu/hodgkinebvmibi/paper_figures/figure2/celltype_log2c.pdf', celltype_log2c, dpi = 320)


```

### Figure 2D


```{r}

for (celltype in unique(hodgkin_annotated$Annotation)){
  p <- hodgkin_annotated %>% 
    group_by(pointNum, Annotation, ebv_status) %>%
    # Generate a df with column: pointNum, Annotation, ebv_status, n
    dplyr::count() %>% 
    ungroup() %>% 
    group_by(pointNum) %>% 
    mutate(total_n = sum(n)) %>% 
    mutate(percent_infil = n/total_n) %>% 
    ungroup() %>% 
    # Subset df based on celltype
    filter(Annotation == celltype) %>% 
    # Plot
    ggplot(aes(x = percent_infil, y = reorder(as.factor(pointNum), percent_infil), fill = ebv_status)) + 
    geom_col() + 
    scale_fill_manual(values = c('Positive' = '#D55E00', 'Negative' = '#009E73')) + 
    theme_bw() + 
    labs(x = 'Proportion Infiltration', y = 'FOV',title = paste0(celltype, ' infiltration'), fill = 'EBV Status') + 
    theme(legend.position = c(0.9, 0.15),
          legend.background=element_rect(fill = alpha("white", 0.5)),
          text = element_text(size = 12)) #+ 
    #facet_wrap(~gender, scales = 'free_y')
  ggsave(filename = paste0('~/hodgkinebvmibi/paper_figures/figure2/figure2d/',celltype,'.pdf'), plot = p, width = 10, height = 10, units = 'in')
    
}

```

### Figure 2E


```{r}

################################################################################################
# df: data frame
# id_col: str, name of identifier column
# celltype_col: str, name of cell type column
# group1_col: str, name of the variable one wants to stratify
# group1_level: a vector thet specifies the levels of group1
# group1_color: a vector like c('a' = color1, 'b' = color2)
# group1_title: str, a title that will later be the name of the heatmap legend
# topic_col: str, default is NULL, specify the name of the CN column if doing CN
# topic_num: str, default is NULL, specify the CN one is interested in 
# marker_vec: str, vector of markers of interest
# celltype_vec: str, vector of cell type of interst
# celltype_color_vec: named str, vector of color for each cell type, c('Tumor' = color1, ....)
# heatmap_tile: str, title of the heatmap 
# draw_heatmap: boolean, default TRUE, if TRUE, print the heatmap
#################################################################################################

marker_heatmap <- function(df, count_df, id_col, celltype_col, 
                           group1_col, group1_level, group1_color, group1_title, 
                           topic_col = NULL, topic_num = NULL, marker_vec, celltype_vec,
                           celltype_color_vec, heatmap_title, draw_heatmap = TRUE, log10_count = FALSE, z_low = -2, z_high = 2){
  
  # Calculate the sample mean and sample standard deviation
  
  pop_stat <- df %>%
    # Select all the columns
    dplyr::select(all_of(id_col), all_of(celltype_col), all_of(group1_col), all_of(marker_vec)) %>% 
    # Pivot longer to get all the markers into the same column for later grouping
    pivot_longer(cols = -c(all_of(id_col), all_of(celltype_col), all_of(group1_col)), names_to = 'marker', values_to = 'value') %>% 
    # Group by marker
    group_by(marker) %>%
    # Calculate the mean and sd 
    summarise(pop_mean = mean(value),
           pop_sd = mean(value))
  
  # If user specifies CN information, calculate stratified sample mean within CN
  if (!is.null(topic_num)){
    stratified_stat <- df %>% 
      # Filter to get cells only within the given CN
      dplyr::filter(!!as.symbol(topic_col) == topic_num) %>%
      # Select columns
      dplyr::select(all_of(id_col), all_of(celltype_col), all_of(group1_col), all_of(marker_vec)) %>%
      # Pivot all the markers into one column
      pivot_longer(cols = -c(all_of(id_col), all_of(celltype_col), all_of(group1_col)), names_to = 'marker', values_to = 'value') %>%
      # Group
      group_by(marker, !!as.symbol(celltype_col), !!as.symbol(group1_col)) %>%
      # Calculate stratified sample mean
      summarise(mu = mean(value)) %>%
      ungroup() %>%
      # Select only celltypes of interest
      dplyr::filter(!!as.symbol(celltype_col) %in% celltype_vec)
    
    
    # Get the count of each celltype for heatmap annotation
    bar_vec <- count_df %>%
      filter(!!as.symbol(topic_col) == topic_num) %>% 
      filter(!!as.symbol(celltype_col) %in% celltype_vec) %>% 
      group_by(!!as.symbol(celltype_col), !!as.symbol(group1_col)) %>% 
      dplyr::count() %>% 
      # log10 count since there are usually a lot of cells
      mutate(log_n = log10(n)) %>% 
      arrange(!!as.symbol(group1_col))
    
    
    # If user doesn't specify CN information, calculate across all cells 
  } else {
    stratified_stat <- df %>% 
      # Select columns
      dplyr::select(all_of(id_col), all_of(celltype_col), all_of(group1_col), all_of(marker_vec)) %>%
      # Pivot markers into one column
      pivot_longer(cols = -c(all_of(id_col), all_of(celltype_col), all_of(group1_col)), names_to = 'marker', values_to = 'value') %>% 
      # Group
      group_by(marker, !!as.symbol(celltype_col), !!as.symbol(group1_col)) %>% 
      # Calculate stratified sample mean
      summarise(mu = mean(value)) %>% 
      ungroup() %>% 
      # Select celltypes of interest
      dplyr::filter(!!as.symbol(celltype_col) %in% celltype_vec)
    
    # Get the count of each celltype for heatmap annotation
    bar_vec <- count_df %>%
      filter(!!as.symbol(celltype_col) %in% celltype_vec) %>% 
      group_by(!!as.symbol(celltype_col), !!as.symbol(group1_col)) %>% 
      dplyr::count() %>% 
      mutate(log_n = log10(n)) %>% 
      arrange(!!as.symbol(group1_col))
  }
  
  # match the rows of stratified_stat with marker x to pop_stat with marker x to append the sample mean to stratified_stat 
  match_idx <- match(stratified_stat$marker, pop_stat$marker)
    
  stratified_stat <- stratified_stat %>% 
    # calculate z score
    mutate(z_score = (mu - pop_stat$pop_mean[match_idx])/pop_stat$pop_sd[match_idx]) %>% 
    # Create a new variable by combining the grouping variable and celltype in order to later split the heatmap
    mutate(celltype_group1 = interaction(!!as.symbol(celltype_col), !!as.symbol(group1_col))) %>% 
    # arrange the variable to make sure same group stays together 
    arrange(celltype_group1)
  
  # Convert stratified_stat into the desired format of the heatmap
  heatmap_df <- stratified_stat %>% 
    dplyr::select(marker, celltype_group1, z_score) %>% 
    pivot_wider(id_cols = 'marker', names_from = 'celltype_group1', values_from = 'z_score')

  heatmap_mat <- heatmap_df %>% 
    column_to_rownames(var = 'marker') %>% 
    as.matrix()
  
  # Create a celltype-color LUT
  color_df <- as.data.frame(celltype_color_vec) %>%
    rownames_to_column('celltype') %>% 
    mutate(celltype = str_extract(celltype, '^[^.]+')) %>% 
    distinct() %>% 
    arrange(celltype)
  
  if (log10_count){
      # heatmap annotation 1, which contains color blocks to indicate the grouping variable and a barplot for the count of each cell type
  column_ha <- HeatmapAnnotation(group1 = factor(str_extract(colnames(heatmap_mat), '(?<=\\.).*'), levels = group1_level),
                               col = list(group1 = group1_color), # color block for grouping variable, order is based on the level specified by the user 
                      # barplot
                               count = anno_barplot(bar_vec$log_n, border = FALSE, bar_width = 0.9,
                                                    gp = gpar(col = 'black', fill = rep(color_df$celltype_color_vec, 2)),
                                                    height = unit(1, 'cm'),
                                                    ylim = c(0,6)),
                               show_annotation_name = FALSE,
                               annotation_legend_param = list(title = group1_title))
  } else {
      # heatmap annotation 1, which contains color blocks to indicate the grouping variable and a barplot for the count of each cell type
  column_ha <- HeatmapAnnotation(group1 = factor(str_extract(colnames(heatmap_mat), '(?<=\\.).*'), levels = group1_level),
                               col = list(group1 = group1_color), # color block for grouping variable, order is based on the level specified by the user 
                      # barplot
                               count = anno_barplot(bar_vec$n, border = FALSE, bar_width = 0.9,
                                                    gp = gpar(col = 'black', fill = rep(color_df$celltype_color_vec, 2)),
                                                    height = unit(1, 'cm')),
                               show_annotation_name = FALSE,
                               annotation_legend_param = list(title = group1_title))
  }
  

  # heatmap annotaiton 2, bottom color blocks for cell type

  column_ha2 <- HeatmapAnnotation(celltype = rep(color_df$celltype,2),
                                  col = list(celltype = celltype_color_vec), show_annotation_name = FALSE,
                                  gp = gpar(col = 'black', lwd = 1),
                                  annotation_legend_param = list(title = 'Cell Type'))
  # Set range for Z score 
  library(circlize)
  col_fun = colorRamp2(c(z_low, 0, z_high), c('#4575b4', "white", '#d73027'))
  
  # Heatmap 
  h <- Heatmap(heatmap_mat, cluster_columns = FALSE, column_split = factor(str_extract(colnames(heatmap_mat), '(?<=\\.).*'), levels = group1_level), cluster_column_slices = FALSE, cluster_rows = FALSE, row_names_side = 'left', rect_gp = gpar(col = "black", lwd = 1), top_annotation = column_ha, column_title = heatmap_title, bottom_annotation = column_ha2, show_column_names = FALSE, name = 'Z Score', heatmap_legend_param = list(border = 'black'), col = col_fun, row_order = marker_vec, width = ncol(heatmap_mat) * unit(5, 'mm'), height = nrow(heatmap_mat) * unit(5, 'mm'))
  
  if (draw_heatmap){
    draw(h)
  }

return(h)  
  
}

```




```{r}


hodgkin_annotated %>% 
  group_by(ebv_status, Annotation) %>% 
  dplyr::count() %>% 
  arrange(Annotation)


core_level <- hodgkin_annotated %>% 
  dplyr::select(pointNum, ebv_status, Annotation, `B2-Microglobulin`, HLA1, `HLA-DR`, CD45RO, Tox, Lag3, `PD-1`, `PD-L1`) %>% 
  pivot_longer(cols = -c(pointNum, ebv_status, Annotation), names_to = 'marker', values_to = 'value') %>% 
  group_by(pointNum, ebv_status, Annotation, marker) %>% 
  summarise(mu = mean(value)) %>% 
  pivot_wider(names_from = 'marker', values_from = 'mu')

pdf('~/hodgkinebvmibi/paper_figures/figure2/figure2e/MHC-1_log10.pdf')

marker_heatmap(core_level, hodgkin_annotated, 'pointNum', 'Annotation', 
               group1_col = 'ebv_status', group1_level = c('Positive', 'Negative'), group1_color = c('Positive' = '#D55E00', 
                                                                                                     'Negative' = '#009E73'),
               'EBV Status', marker_vec = c('B2-Microglobulin', 'HLA1'), celltype_vec = c('CD4', 'CD8', 'Cytotoxic CD4', 'Cytotoxic CD8', 'Endothelial', 'Neutrophil', 'NK', 'Treg'),
               celltype_color_vec = celltype_color[c('CD4', 'CD8', 'Cytotoxic CD4', 'Cytotoxic CD8', 'Endothelial', 'Neutrophil', 'NK', 'Treg')], heatmap_title = 'MHC-I', log10_count = TRUE, draw_heatmap = TRUE, z_low = -1, z_high = 1)

dev.off()

pdf('~/hodgkinebvmibi/paper_figures/figure2/figure2e/MHC-2_log10.pdf')

marker_heatmap(core_level, hodgkin_annotated, 'pointNum', 'Annotation', 
               group1_col = 'ebv_status', group1_level = c('Positive', 'Negative'), group1_color = c('Positive' = '#D55E00', 
                                                                                                     'Negative' = '#009E73'),
               'EBV Status', marker_vec = c('B2-Microglobulin', 'HLA1', 'HLA-DR'), celltype_vec = c('B', 'DC', 'M1', 'M2', 'Tumor'),
               celltype_color_vec = celltype_color[c('B', 'DC', 'M1', 'M2', 'Tumor')], heatmap_title = 'MHC-II', log10_count = TRUE, draw_heatmap = FALSE,
               z_low = -1, z_high = 1)

dev.off()


pdf('~/hodgkinebvmibi/paper_figures/figure2/figure2e/Exhaustion_log10.pdf')

marker_heatmap(core_level, hodgkin_annotated, 'pointNum', 'Annotation', 
               group1_col = 'ebv_status', group1_level = c('Positive', 'Negative'), group1_color = c('Positive' = '#D55E00', 
                                                                                                     'Negative' = '#009E73'),
               'EBV Status', marker_vec = c('CD45RO', 'Tox', 'Lag3', 'PD-1'), celltype_vec = c('CD4', 'CD8', 'Cytotoxic CD4', 'Cytotoxic CD8', 'Treg'),
               celltype_color_vec = celltype_color[c('CD4', 'CD8', 'Cytotoxic CD4', 'Cytotoxic CD8', 'Treg')], heatmap_title = 'Exhaustion', log10_count = TRUE, draw_heatmap = FALSE,
               z_low = -1, z_high = 1)

dev.off()

pdf('~/hodgkinebvmibi/paper_figures/figure2/figure2e/Exhaustion_other_log10.pdf')

marker_heatmap(core_level, hodgkin_annotated, 'pointNum', 'Annotation', 
               group1_col = 'ebv_status', group1_level = c('Positive', 'Negative'), group1_color = c('Positive' = '#D55E00', 
                                                                                                     'Negative' = '#009E73'),
               'EBV Status', marker_vec = c('PD-L1'), celltype_vec = c('DC', 'M1', 'M2', 'Tumor'),
               celltype_color_vec = celltype_color[c('DC', 'M1', 'M2', 'Tumor')], heatmap_title = 'Exhaustion', log10_count = TRUE, draw_heatmap = FALSE,
               z_low = -1, z_high = 1)

dev.off()
  



```




## Figure 3

### Figure 3A

```{r}

df_topic <- read_csv('~/hodgkinebvmibi/clustering_data/final_df_with_topic_032123.csv')

LDA_pop_mean_df <- df_topic %>% 
  group_by(topic, Annotation) %>% 
  dplyr::count() %>% 
  ungroup() %>% 
  group_by(Annotation) %>% 
  summarise(pop_mean = mean(n),
            pop_sd = sd(n))

LDA_mean_df <- df_topic %>% 
  group_by(topic, Annotation) %>% 
  dplyr::count() %>% 
  ungroup()

LDA_mean_df <- LDA_mean_df %>% 
  mutate(pop_mean = LDA_pop_mean_df$pop_mean[match(LDA_mean_df$Annotation, LDA_pop_mean_df$Annotation)],
         pop_sd = LDA_pop_mean_df$pop_sd[match(LDA_mean_df$Annotation, LDA_pop_mean_df$Annotation)]) %>% 
  mutate(z_new = (n - pop_mean)/pop_sd)

LDA_heatmap_df <- LDA_mean_df %>% 
  dplyr::select(topic, z_new, Annotation) %>% 
  pivot_wider(names_from = 'topic', values_from = 'z_new')

heatmap_mat <- as.matrix(LDA_heatmap_df[,2:9])

rownames(heatmap_mat) <- LDA_heatmap_df$Annotation

library(circlize)
col_fun = colorRamp2(c(-1, 0, 1), c('#4575b4', "white", '#d73027'))

bar_vec <- df_topic %>% 
  group_by(topic) %>% 
  dplyr::count()

column_ha <- HeatmapAnnotation(count = anno_barplot(bar_vec$n))

Heatmap(heatmap_mat, cluster_rows = FALSE, cluster_columns  = FALSE, col = col_fun, name = 'Z Score', clustering_method_columns = 'complete',
        row_names_side = 'left', top_annotation = column_ha, column_names_gp = grid::gpar(fontsize = 12),
  row_names_gp = grid::gpar(fontsize = 12), rect_gp = gpar(col = "black", lwd = 2))

```


### Figure 3B
```{r}

df_topic <- read_csv('~/hodgkinebvmibi/clustering_data/final_df_with_topic_032123.csv')


df_topic <- df_topic %>% 
  mutate(ebv_status = hodgkin_annotated$ebv_status[match(df_topic$patientID, hodgkin_annotated$patientID)])


p <- df_topic %>% 
  filter(ebv_status != 'control') %>% 
  mutate(ebv_status = factor(ebv_status, levels = c('Positive', 'Negative'))) %>% 
  group_by(pointNum, topic, ebv_status) %>% 
  dplyr::count() %>% 
  ungroup() %>% 
  group_by(pointNum) %>% 
  mutate(total_n = sum(n)) %>% 
  group_by(pointNum, topic) %>% 
  mutate(prop = n/total_n) %>% 
  ungroup() %>% 
  ggplot(aes(x = as.factor(pointNum), y = prop, color = topic)) + 
  geom_point(aes(alpha = prop)) + 
  geom_segment(aes(x = as.factor(pointNum), xend = as.factor(pointNum), y = 0, yend = prop, color = topic)) + 
  coord_flip() + 
  facet_grid(vars(ebv_status), vars(topic), scales = 'free_y') + 
  theme_bw() + 
  scale_color_brewer(palette = 'Set2') + 
  theme(panel.grid.major.y = element_blank(),
        legend.position = 'bottom')


p <- df_topic %>% 
  filter(ebv_status != 'control') %>% 
  mutate(ebv_status = factor(ebv_status, levels = c('Positive', 'Negative'))) %>% 
  group_by(pointNum, topic, ebv_status) %>% 
  dplyr::count() %>% 
  ungroup() %>% 
  group_by(pointNum) %>% 
  mutate(total_n = sum(n)) %>% 
  group_by(pointNum, topic) %>% 
  mutate(prop = n/total_n) %>% 
  ungroup() %>% 
  ggplot(aes(x = as.factor(pointNum), y = topic, color = topic)) + 
  geom_point(aes(size = prop), alpha = 1) + 
  #geom_segment(aes(x = as.factor(pointNum), xend = as.factor(pointNum), y = 0, yend = prop, color = topic)) + 
  facet_wrap(~ebv_status, scales = 'free_x') +
  theme_bw() + 
  scale_color_brewer(palette = 'Set2') + 
  scale_size_continuous(range = c(0,10)) + 
  theme(panel.grid.major.y = element_blank(),
        legend.position = 'bottom')

ggsave('~/hodgkinebvmibi/paper_figures/figure3b_2.pdf', p, width = 15, height = 5, unit = 'in')

View(df_topic %>% 
  filter(ebv_status != 'control') %>% 
  mutate(ebv_status = factor(ebv_status, levels = c('Positive', 'Negative'))) %>% 
  group_by(pointNum, topic, ebv_status) %>% 
  dplyr::count() %>% 
  ungroup() %>% 
  group_by(pointNum) %>% 
  mutate(total_n = sum(n)) %>% 
  group_by(pointNum, topic) %>% 
  mutate(prop = n/total_n) %>% 
  filter(topic %in% c('Topic-0', 'Topic-1')))


df_topic %>% 
  filter(ebv_status != 'control') %>% 
  mutate(ebv_status = factor(ebv_status, levels = c('Positive', 'Negative'))) %>% 
  group_by(pointNum, topic, ebv_status) %>% 
  dplyr::count() %>% 
  ungroup() %>% 
  group_by(pointNum) %>% 
  mutate(total_n = sum(n)) %>% 
  group_by(pointNum, topic) %>% 
  mutate(prop = n/total_n) %>% 
  group_by(pointNum, ebv_status) %>% 
  mutate(order_vec = n[topic == 'Topic-0']/sum(n)) %>% 
  ungroup() %>% 
  ggplot(aes(x = reorder(as.factor(pointNum), order_vec), y = prop, fill = topic)) + 
  geom_col(position = 'dodge') + 
  facet_wrap(~ebv_status, scale = 'free_x') + 
  theme_bw() + 
  scale_fill_brewer(palette = 'Set2') + 
  theme(panel.grid.major.x = element_blank())

```


### Figure 3C

```{r}

p <- df_topic %>% 
  mutate(ebv_status = factor(ebv_status, levels = c('Negative', 'Positive'))) %>% 
  #mutate(topic = factor(topic, levels = c('topic-0', 'topic-1', 'topic-2', 'topic-3', 'topic-4', 'topic-5', 'topic-6', 'topic-7'))) %>% 
  group_by(topic, ebv_status) %>% 
  dplyr::count() %>% 
  dplyr::filter(ebv_status != 'control') %>% 
  ungroup() %>% 
  group_by(ebv_status) %>% 
  mutate(total_n = sum(n)) %>% 
  ungroup() %>% 
  group_by(topic) %>% 
  mutate(diff = log2((n/total_n) / (lag(n)/lag(total_n)))) %>% 
  drop_na() %>% 
  ggplot(aes(x = reorder(topic, diff), y = diff, fill = topic)) +
  geom_col() + 
  geom_rect(aes(xmin = 0, ymin = 0, xmax = Inf, ymax = Inf), fill = '#D55E00', alpha = 0.02) + 
  geom_rect(aes(xmin = 0, ymin = -Inf, xmax = Inf, ymax = 0), fill = '#009E73', alpha = 0.02) + 
  #annotate('text', x = 1, y = 1.5, label = 'EBV+', size = 12) +
  #annotate('text', x = 7, y = -6, label = 'EBV-', size = 12) +
  labs(x = 'Neighborhood', y = 'Log2 Fold Enrichment', title = 'Neighborhood Enrichment (EBV+/EBV-)') + 
  scale_fill_manual('Neighborhood', values = c('Topic-0' = '#66C2A5', 'Topic-1' = '#FC8D62', 'Topic-2' = '#8DA0CB', 'Topic-3' = '#E78AC3', 'Topic-4' = '#A6D854', 'Topic-5' = '#FFD92F',
                                               'Topic-6' = '#E5C494', 'Topic-7' = '#B3B3B3'), na.value = 'white', na.translate = TRUE) +
  #scale_fill_brewer(palette = 'Set2') +
  theme_bw() + 
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5),
        legend.position = 'right',
        text = element_text(size = 12))

ggsave('/mnt/nfs/home/huayingqiu/hodgkinebvmibi/paper_figures/figure3/log2fold.pdf', p, dpi = 320)

```



### Figure 3D
```{r}


# df_topic %>% 
#   filter(topic %in% c('Topic-0', 'Topic-1', 'Topic-6')) %>% 
#   group_by(pointNum, topic, Annotation, ebv_status) %>% 
#   count() %>% 
#   group_by(pointNum, topic) %>% 
#   mutate(total_n = sum(n)) %>% 
#   group_by(pointNum, topic, Annotation) %>% 
#   mutate(prop = n/total_n) %>% 
#   filter(Annotation %in% c('CD4', 'CD8', 'Cytotoxic CD4', 'Cytotoxic CD8', 'Treg', 'M1', 'M2', 'Dc', 'Tumor')) %>% 
#   ggplot(aes(x = interaction(ebv_status, topic), y = prop)) + 
#   # geom_rect(xmin= 0, xmax=3.5, ymin=-Inf, ymax=Inf, 
#   #           fill="#D55E00", alpha = 0.01) +
#   # geom_rect(xmin= 3.5, xmax=Inf, ymin=-Inf, ymax=Inf, 
#   #           fill="#009E73", alpha = 0.01) +
#   geom_boxplot(aes(fill = interaction(ebv_status, topic)), outlier.alpha = 0) +
#   geom_jitter(alpha = 0.3, position = position_jitter(0.1)) + 
#   facet_wrap(~Annotation, scales = 'free_y') + 
#   scale_fill_manual(values = c('Positive.Topic-0' = '#D55E00', 'Positive.Topic-1' = '#D55E00', 'Positive.Topic-6' = '#D55E00',
#                                'Negative.Topic-0' = '#009E73', 'Negative.Topic-1' = '#009E73', 'Negative.Topic-6' = '#009E73')) + 
#   stat_compare_means(comparisons = list(c('Positive.Topic-0', 'Negative.Topic-0'),
#                                          c('Positive.Topic-1', 'Negative.Topic-1'),
#                                          c('Positive.Topic-6', 'Negative.Topic-6')), label = 'p.signif') + 
#   #scale_color_manual(values = c('Positive' = '#D55E00', 'Negative' = '#009E73')) + 
#   theme_bw()
  
for (i in unique(df_topic$Annotation)){
  p <- df_topic %>% 
  filter(topic %in% c('Topic-0', 'Topic-1')) %>% 
  group_by(pointNum, topic, Annotation, ebv_status) %>% 
  count() %>% 
  group_by(pointNum, topic) %>% 
  mutate(total_n = sum(n)) %>% 
  group_by(pointNum, topic, Annotation) %>% 
  mutate(prop = n/total_n) %>% 
  filter(Annotation == i) %>% 
  ggplot(aes(x = interaction(ebv_status, topic), y = prop)) + 
  # geom_rect(xmin= 0, xmax=3.5, ymin=-Inf, ymax=Inf, 
  #           fill="#D55E00", alpha = 0.01) +
  # geom_rect(xmin= 3.5, xmax=Inf, ymin=-Inf, ymax=Inf, 
  #           fill="#009E73", alpha = 0.01) +
  geom_boxplot(aes(fill = interaction(ebv_status, topic)), outlier.alpha = 0) +
  geom_jitter(alpha = 0.3, position = position_jitter(0.1)) + 
  scale_fill_manual(values = c('Positive.Topic-0' = '#D55E00', 'Positive.Topic-1' = '#D55E00', 'Positive.Topic-6' = '#D55E00',
                               'Negative.Topic-0' = '#009E73', 'Negative.Topic-1' = '#009E73', 'Negative.Topic-6' = '#009E73')) + 
  stat_compare_means(comparisons = list(c('Positive.Topic-0', 'Negative.Topic-0'),
                                         c('Positive.Topic-1', 'Negative.Topic-1')), label = 'p.signif') + 
  #scale_color_manual(values = c('Positive' = '#D55E00', 'Negative' = '#009E73')) + 
  theme_bw() + 
  labs(title = i) + 
  theme(legend.position = 'none',
        axis.text.x = element_text(angle = 90))
  
  ggsave(paste0('~/hodgkinebvmibi/paper_figures/celltype_topic_compare_102423/', i, '.pdf'), p, width = 6, height = 6, units = 'in')
}

```

### Figure 3E



```{r}

CN_core_level <- df_topic %>% 
  dplyr::select(pointNum, ebv_status, Annotation, `B2-Microglobulin`, HLA1, `HLA-DR`, CD45RO, Tox, Lag3, `PD-1`, `PD-L1`, topic) %>% 
  pivot_longer(cols = -c(pointNum, ebv_status, Annotation, topic), names_to = 'marker', values_to = 'value') %>% 
  group_by(pointNum, ebv_status, Annotation, marker, topic) %>% 
  summarise(mu = mean(value)) %>% 
  pivot_wider(names_from = 'marker', values_from = 'mu')

CN_core_level %>% 
  filter(topic %in% c('Topic-0', 'Topic-1')) %>%
  ggplot(aes(x = topic, y = `B2-Microglobulin`, fill = topic)) + 
  geom_boxplot() + 
  facet_wrap(~ebv_status + Annotation)

CN_core_level %>% 
  filter(topic %in% c('Topic-0', 'Topic-1')) %>% 
  filter(Annotation == 'CD4') %>%
  filter(ebv_status == 'Negative')


marker_heatmap(core_level, hodgkin_annotated, 'pointNum', 'Annotation', 
               group1_col = 'ebv_status', group1_level = c('Positive', 'Negative'), group1_color = c('Positive' = '#D55E00', 
                                                                                                     'Negative' = '#009E73'),
               'EBV Status', marker_vec = c('CD45RO', 'Tox', 'Lag3', 'PD-1'), celltype_vec = c('CD4', 'CD8', 'Cytotoxic CD4', 'Cytotoxic CD8', 'Treg'),
               celltype_color_vec = celltype_color[c('CD4', 'CD8', 'Cytotoxic CD4', 'Cytotoxic CD8', 'Treg')], heatmap_title = 'Exhaustion', log10_count = FALSE, draw_heatmap = FALSE)




df_topic %>%
      filter(Annotation %in% c('CD4', 'CD8', 'Cytotoxic CD4', 'Cytotoxic CD8', 'Treg')) %>% 
      group_by(Annotation, ebv_status, topic) %>% 
      dplyr::count() %>% 
      mutate(log_n = log10(n)) %>% 
      arrange(ebv_status)

```




```{r}

pdf('~/hodgkinebvmibi/paper_figures/figure3/figure3e/T_cells.pdf')

h1 <- marker_heatmap(CN_core_level, count_df = df_topic, 'pointNum', 'Annotation', 'ebv_status', c('Positive', 'Negative'), c('Positive' = '#D55E00', 'Negative' = '#009E73'), 'EBV Status', topic_col = 'topic', topic_num = 'Topic-0', marker_vec = c('B2-Microglobulin', 'HLA1', 'CD45RO', 'Tox', 'Lag3', 'PD-1'), celltype_vec = c('CD4', 'CD8', 'Cytotoxic CD4', 'Cytotoxic CD8', 'Treg'), celltype_color_vec = c('CD4' = '#4DAF4A', 'CD8' = '#984EA3', 'Cytotoxic CD4' = '#253d24', 'Cytotoxic CD8' = '#FF7F00', 'Treg' = '#BEBADA'), heatmap_title = 'CN0', log10_count = TRUE, draw_heatmap = FALSE, z_low = -1, z_high = 1)


h2 <- marker_heatmap(CN_core_level, df_topic, 'pointNum', 'Annotation', 'ebv_status', c('Positive', 'Negative'), c('Positive' = '#D55E00', 'Negative' = '#009E73'), 'EBV Status', topic_col = 'topic', topic_num = 'Topic-1', marker_vec = c('B2-Microglobulin', 'HLA1', 'CD45RO', 'Tox', 'Lag3', 'PD-1'), celltype_vec = c('CD4', 'CD8', 'Cytotoxic CD4', 'Cytotoxic CD8', 'Treg'), celltype_color_vec = c('CD4' = '#4DAF4A', 'CD8' = '#984EA3', 'Cytotoxic CD4' = '#253d24', 'Cytotoxic CD8' = '#FF7F00', 'Treg' = '#BEBADA'), heatmap_title = 'CN1', log10_count = TRUE, draw_heatmap = FALSE, z_low = -1, z_high = 1)


heatmap_list <- h1+h2

draw(heatmap_list, ht_gap = unit(1, 'cm'))

dev.off()

```



```{r}

pdf('~/hodgkinebvmibi/paper_figures/figure3/figure3e/Other_cells.pdf')

h3 <- marker_heatmap(CN_core_level, df_topic, 'pointNum', 'Annotation', 'ebv_status', c('Positive', 'Negative'), c('Positive' = '#D55E00', 'Negative' = '#009E73'), 'EBV Status', topic_col = 'topic', topic_num = 'Topic-0', marker_vec = c('B2-Microglobulin', 'HLA1', 'HLA-DR', 'PD-L1'), celltype_vec = c('DC', 'M1', 'M2', 'Tumor'), celltype_color_vec = c('DC' = '#377EB8', 'M2' = '#f7c173', 'M1' = '#00FFFF', 'Tumor' = '#E41A1C'), heatmap_title = 'CN0', log10_count = TRUE, draw_heatmap = FALSE, z_low = -1, z_high = 1)

h4 <- marker_heatmap(CN_core_level, df_topic, 'pointNum', 'Annotation', 'ebv_status', c('Positive', 'Negative'), c('Positive' = '#D55E00', 'Negative' = '#009E73'), 'EBV Status', topic_col = 'topic', topic_num = 'Topic-1', marker_vec = c('B2-Microglobulin', 'HLA1', 'HLA-DR', 'PD-L1'), celltype_vec = c('DC', 'M1', 'M2', 'Tumor'), celltype_color_vec = c('DC' = '#377EB8', 'M2' = '#f7c173', 'M1' = '#00FFFF', 'Tumor' = '#E41A1C'), heatmap_title = 'CN1', log10_count = TRUE, draw_heatmap = FALSE, z_low = -1, z_high = 1)

heatmap_list <- h3+h4

draw(heatmap_list, ht_gap = unit(1, 'cm'))

dev.off()


```


## Figure 4

### Figure 4B


```{r}


# Plot out the cells in phenomaps

library(raster)

seg_list <- list.files('~/hodgkinebvmibi/20220823_cHL-DFCI_Production_M060/', full.names = TRUE, recursive = TRUE, pattern = 'segmentationMap.tif')

# Exchange position of masks of the two LN

seg_list <- replace(seg_list, c(31,32), seg_list[c(32,31)])

# Read in segmentation mask

mask_list <- map(seg_list, function(x){
  as.matrix(raster(x))
})


# Join the bins and scores to the original data

bin_score_df <- hodgkin_tumor_score_100um %>% 
  dplyr::select(pointNum, cellLabel, centroidX, centroidY, score, bin, bin_deriva)


hodgkin_annotated <- hodgkin_annotated %>% 
  left_join(bin_score_df, by = c('pointNum', 'cellLabel', 'centroidX', 'centroidY'))

hodgkin_annotated %>% 
  dplyr::select(Annotation, bin, bin_deriva) %>% 
  filter(Annotation == 'Tumor')

hodgkin_annotated <- hodgkin_annotated %>% 
  mutate(bin = ifelse(is.na(bin), 'Tumor', bin),
         bin_deriva = ifelse(is.na(bin_deriva), 'Tumor', bin_deriva))




```


```{r}


new_annotation <- hodgkin_annotated %>% 
  dplyr::filter(is.na(fov)) %>% 
  dplyr::select(pointNum, patientID, region, bin_deriva, cellLabel)

pointNum_ID_region_LUT <- new_annotation %>% 
  group_by(pointNum, patientID, region) %>% 
  dplyr::count() %>% 
  dplyr::select(-n)

celltype_plot <- function(point_num, seg_list, annotation, cell_label, mypalette, pointNumLUT, verbose = FALSE, out = FALSE, out_path = NULL, print_fig = FALSE){
  require(reshape2)
  require(purrr)
  require(ggplot2)
  require(dplyr)
  require(tidyr)
  # Get segmentation matrix
  seg_mat <- seg_list[[point_num - 2]]
  # Get segmentation outline
  #seg_outline <- outline[[point_num - 2]]
  # Get cell types for this point. Stored as a list
  cell_type <- as.list(unique(annotation))
  # Store cell label of each cell type in a list
  type_label_LUT <- map(cell_type, function(x){
    cell_label[annotation == x]
  })
  # Name list by cell type
  names(type_label_LUT) <- unique(annotation)
  # Reshape segmentation matrix and add a column called pixel type
  mat_long <- melt(seg_mat)
  mat_long <- mat_long %>% 
    mutate(pixel_type = rep(NA, nrow(mat_long)))
  # outline_long <- melt(seg_outline)
  # outline_long <- outline_long %>%
  # mutate(pixel = ifelse(value == 1, 'outline', NA))
  # Fill in pixel type by cell type
  for (i in 1:length(unique(annotation))){
    mat_long$pixel_type[mat_long$value %in% type_label_LUT[[i]]] <- unique(annotation)[i]
  }
  # Match cell type and color to make sure color is uniform across the board
  color <- mypalette$color[match(unique(annotation), mypalette$celltype)]
  # Match pointNum, patientID, and region
  plot_title <- paste0(pointNumLUT$patientID[pointNumLUT$pointNum == point_num], '_', pointNumLUT$region[pointNumLUT$pointNum == point_num])
  # Plot 
  p <- ggplot()+
    #geom_tile(data = outline_long, aes(x = Var2, y = -Var1, fill = as.factor(pixel))) + 
    #scale_fill_manual(values = c('#FFFFFF'), na.value = 'white', na.translate = FALSE) + 
    geom_raster(data = mat_long, aes(x = Var2, y = -Var1, fill = pixel_type)) + 
    scale_fill_manual('Bin', values = c('Tumor' = '#E41A1C', 'Tumor Dense' = '#f6adff', 'Tumor Sparse' = '#e1d936', 'Far' = '#52bcaa'), na.value = 'white', drop = FALSE) + 
    #scale_fill_viridis_d() + 
    #labs(title = paste0(plot_title), fill = 'Cell Types') + 
    theme(axis.title = element_blank(),
          axis.ticks = element_blank(),
          axis.line = element_blank(),
          axis.text = element_blank(),
          panel.background = element_blank(),
          panel.grid = element_blank(),
          legend.position = 'none')
  # Show plot
  if (verbose){
    cat('Plot for PointNum ', point_num, ' completed. \n')
  }
  if (out){
    ggsave(filename = paste0(out_path, plot_title, '.png'), plot = p, device = 'png', height = 9, width = 9, units = 'in', dpi = 320)
    #legend_plot <- cowplot::get_legend(p)
    #ggsave(filename = paste0(out_path, 'legend.pdf'), plot = legend_plot, device = 'pdf', dpi = 320)
  }
  if (print_fig){
    print(p)
  }
}

```


```{r}


library(foreach)

mypalette <- data.frame(celltype = c('Tumor', 'Tumor Dense', 'Tumor Sparse', 'Far'),
                        color = c('#E41A1C', '#a03f38', '#1cf1a3', '#94d3bc'))

cl <- parallel::makeCluster(20)
doParallel::registerDoParallel(cl)

foreach (i = unique(new_annotation$pointNum)) %dopar% {
  celltype_plot(i, mask_list, new_annotation$bin_deriva[new_annotation$pointNum == i], new_annotation$cellLabel[new_annotation$pointNum == i], mypalette = mypalette, pointNumLUT = pointNum_ID_region_LUT, verbose = TRUE, out = TRUE, out_path = '~/hodgkinebvmibi/paper_figures/bin_map_tangent_no_legend/')
}

parallel::stopCluster(cl)

```



```{r}

new_annotation <- hodgkin_annotated %>% 
  dplyr::filter(!is.na(fov)) %>% 
  dplyr::select(pointNum, patientID, fov, bin_deriva, cellLabel)

pointNum_ID_region_LUT <- new_annotation %>% 
  group_by(pointNum, patientID, fov) %>% 
  dplyr::count() %>% 
  dplyr::select(-n)

celltype_plot <- function(point_num, seg_list, annotation, cell_label, mypalette, pointNumLUT, verbose = FALSE, out = FALSE, out_path = NULL, print_fig = FALSE){
  require(reshape2)
  require(purrr)
  require(ggplot2)
  require(dplyr)
  require(tidyr)
  # Get segmentation matrix
  seg_mat <- seg_list[[point_num - 34]]
  # Get segmentation outline
  #seg_outline <- outline[[point_num - 2]]
  # Get cell types for this point. Stored as a list
  cell_type <- as.list(unique(annotation))
  # Store cell label of each cell type in a list
  type_label_LUT <- map(cell_type, function(x){
    cell_label[annotation == x]
  })
  # Name list by cell type
  names(type_label_LUT) <- unique(annotation)
  # Reshape segmentation matrix and add a column called pixel type
  mat_long <- melt(seg_mat)
  mat_long <- mat_long %>% 
    mutate(pixel_type = rep(NA, nrow(mat_long)))
  # outline_long <- melt(seg_outline)
  # outline_long <- outline_long %>%
  # mutate(pixel = ifelse(value == 1, 'outline', NA))
  # Fill in pixel type by cell type
  for (i in 1:length(unique(annotation))){
    mat_long$pixel_type[mat_long$value %in% type_label_LUT[[i]]] <- unique(annotation)[i]
  }
  # Match cell type and color to make sure color is uniform across the board
  color <- mypalette$color[match(unique(annotation), mypalette$celltype)]
  # Match pointNum, patientID, and region
  plot_title <- paste0(pointNumLUT$patientID[pointNumLUT$pointNum == point_num], '_', pointNumLUT$fov[pointNumLUT$pointNum == point_num])
  # Plot 
  p <- ggplot()+
    #geom_tile(data = outline_long, aes(x = Var2, y = -Var1, fill = as.factor(pixel))) + 
    #scale_fill_manual(values = c('#FFFFFF'), na.value = 'white', na.translate = FALSE) + 
    geom_raster(data = mat_long, aes(x = Var2, y = -Var1, fill = pixel_type)) + 
    scale_fill_manual('Bin', values = c('Tumor' = '#E41A1C', 'Tumor Dense' = '#f6adff', 'Tumor Sparse' = '#e1d936', 'Far' = '#52bcaa'), na.value = 'white', drop = FALSE) + 
    #scale_fill_viridis_d() + 
    #labs(title = paste0(plot_title), fill = 'Cell Types') + 
    theme(axis.title = element_blank(),
          axis.ticks = element_blank(),
          axis.line = element_blank(),
          axis.text = element_blank(),
          panel.background = element_blank(),
          panel.grid = element_blank(),
          legend.position = 'none')
  # Show plot
  if (verbose){
    cat('Plot for PointNum ', point_num, ' completed. \n')
  }
  if (out){
    ggsave(filename = paste0(out_path, plot_title, '.png'), plot = p, device = 'png', height = 9, width = 9, units = 'in', dpi = 320)
    #legend_plot <- cowplot::get_legend(p)
    #ggsave(filename = paste0(out_path, 'legend.pdf'), plot = legend_plot, device = 'pdf', dpi = 320)
  }
  if (print_fig){
    print(p)
  }
}

```


```{r}

library(foreach)

mypalette <- data.frame(celltype = c('Tumor', 'Tumor Dense', 'Tumor Sparse', 'Far'),
                        color = c('#E41A1C', '#a03f38', '#1cf1a3', '#94d3bc'))

cl <- parallel::makeCluster(20)
doParallel::registerDoParallel(cl)

foreach (i = unique(new_annotation$pointNum)) %dopar% {
  celltype_plot(i, mask_list, new_annotation$bin_deriva[new_annotation$pointNum == i], new_annotation$cellLabel[new_annotation$pointNum == i], mypalette = mypalette, pointNumLUT = pointNum_ID_region_LUT, verbose = TRUE, out = TRUE, out_path = '~/hodgkinebvmibi/paper_figures/bin_map_tangent_singleFOV_no_legend/')
}

parallel::stopCluster(cl)

```


```{r}


new_annotation <- hodgkin_annotated %>% 
  dplyr::filter(is.na(fov)) %>% 
  dplyr::select(pointNum, patientID, region, score, cellLabel)

pointNum_ID_region_LUT <- new_annotation %>% 
  group_by(pointNum, patientID, region) %>% 
  dplyr::count() %>% 
  dplyr::select(-n)

celltype_plot <- function(point_num, seg_list, score, cell_label, mypalette, pointNumLUT, verbose = FALSE, out = FALSE, out_path = NULL, print_fig = FALSE){
  require(reshape2)
  require(purrr)
  require(ggplot2)
  require(dplyr)
  require(tidyr)
  # Get segmentation matrix
  seg_mat <- seg_list[[point_num - 2]]
  # Get segmentation outline
  #seg_outline <- outline[[point_num - 2]]
  # tumor score LUT
  tumor_score_LUT <- data.frame(cellLabel = cell_label,
                                tumor_score = score)
  # Reshape segmentation matrix and add a column called pixel type
  mat_long <- melt(seg_mat)
  mat_long <- mat_long %>% 
    mutate(pixel_score = rep(NA, nrow(mat_long)))
  # outline_long <- melt(seg_outline)
  # outline_long <- outline_long %>%
  # mutate(pixel = ifelse(value == 1, 'outline', NA))
  # Fill in pixel type by cell type
  mat_long$pixel_score <- tumor_score_LUT$tumor_score[match(mat_long$value, tumor_score_LUT$cellLabel)]
  # Match pointNum, patientID, and region
  plot_title <- paste0(pointNumLUT$patientID[pointNumLUT$pointNum == point_num], '_', pointNumLUT$region[pointNumLUT$pointNum == point_num])
  # Plot 
  p <- ggplot()+
    #geom_tile(data = outline_long, aes(x = Var2, y = -Var1, fill = as.factor(pixel))) + 
    #scale_fill_manual(values = c('#FFFFFF'), na.value = 'white', na.translate = FALSE) + 
    geom_raster(data = mat_long, aes(x = Var2, y = -Var1, fill = pixel_score)) + 
    #scale_fill_manual('Bin', values = c('Tumor' = '#E41A1C', 'Tumor Proximal' = '#756BB1', 'Tumor Distal' = '#3182BD', 'Far' = '#31A354'), na.value = 'white', drop = FALSE) + 
    scale_fill_viridis_c(option = 'plasma', na.value = 'white') + 
    labs(fill = 'Tumor Score') + 
    #labs(title = paste0(plot_title), fill = 'Cell Types') + 
    theme(axis.title = element_blank(),
          axis.ticks = element_blank(),
          axis.line = element_blank(),
          axis.text = element_blank(),
          panel.background = element_blank(),
          panel.grid = element_blank(),
          legend.position = 'right',
          legend.key.size = unit(1, 'cm'))
  # Show plot
  if (verbose){
    cat('Plot for PointNum ', point_num, ' completed. \n')
  }
  if (out){
    ggsave(filename = paste0(out_path, plot_title, '.png'), plot = p, device = 'png', height = 9, width = 9, units = 'in', dpi = 320)
    #legend_plot <- cowplot::get_legend(p)
    #ggsave(filename = paste0(out_path, 'legend.pdf'), plot = legend_plot, device = 'pdf', dpi = 320)
  }
  if (print_fig){
    print(p)
  }
}


```


```{r}

library(foreach)

mypalette <- data.frame(celltype = c('Tumor', 'Tumor Proximal', 'Tumor Distal', 'Far'),
                        color = c('#E41A1C', '#393B79', '#5254A3', '#6B6ECF'))

cl <- parallel::makeCluster(20)
doParallel::registerDoParallel(cl)

foreach (i = unique(new_annotation$pointNum)) %dopar% {
  celltype_plot(i, mask_list, new_annotation$score[new_annotation$pointNum == i], new_annotation$cellLabel[new_annotation$pointNum == i], mypalette = mypalette, pointNumLUT = pointNum_ID_region_LUT, verbose = TRUE, out = TRUE, out_path = '~/hodgkinebvmibi/paper_figures/score_map_072723/')
}

parallel::stopCluster(cl)

```

```{r}

new_annotation <- hodgkin_annotated %>% 
  dplyr::filter(!is.na(fov)) %>% 
  dplyr::select(pointNum, patientID, fov, score, cellLabel)

pointNum_ID_region_LUT <- new_annotation %>% 
  group_by(pointNum, patientID, fov) %>% 
  dplyr::count() %>% 
  dplyr::select(-n)

celltype_plot <- function(point_num, seg_list, score, cell_label, mypalette, pointNumLUT, verbose = FALSE, out = FALSE, out_path = NULL, print_fig = FALSE){
  require(reshape2)
  require(purrr)
  require(ggplot2)
  require(dplyr)
  require(tidyr)
  # Get segmentation matrix
  seg_mat <- seg_list[[point_num - 34]]
  # Get segmentation outline
  #seg_outline <- outline[[point_num - 2]]
  # tumor score LUT
  tumor_score_LUT <- data.frame(cellLabel = cell_label,
                                tumor_score = score)
  # Reshape segmentation matrix and add a column called pixel type
  mat_long <- melt(seg_mat)
  mat_long <- mat_long %>% 
    mutate(pixel_score = rep(NA, nrow(mat_long)))
  # outline_long <- melt(seg_outline)
  # outline_long <- outline_long %>%
  # mutate(pixel = ifelse(value == 1, 'outline', NA))
  # Fill in pixel type by cell type
  mat_long$pixel_score <- tumor_score_LUT$tumor_score[match(mat_long$value, tumor_score_LUT$cellLabel)]
  # Match pointNum, patientID, and region
  plot_title <- paste0(pointNumLUT$patientID[pointNumLUT$pointNum == point_num], '_', pointNumLUT$fov[pointNumLUT$pointNum == point_num])
  # Plot 
  p <- ggplot()+
    #geom_tile(data = outline_long, aes(x = Var2, y = -Var1, fill = as.factor(pixel))) + 
    #scale_fill_manual(values = c('#FFFFFF'), na.value = 'white', na.translate = FALSE) + 
    geom_raster(data = mat_long, aes(x = Var2, y = -Var1, fill = pixel_score)) + 
    #scale_fill_manual('Bin', values = c('Tumor' = '#E41A1C', 'Tumor Proximal' = '#756BB1', 'Tumor Distal' = '#3182BD', 'Far' = '#31A354'), na.value = 'white', drop = FALSE) + 
    scale_fill_viridis_c(option = 'plasma', na.value = 'white') + 
    labs(fill = 'Tumor Score') + 
    #labs(title = paste0(plot_title), fill = 'Cell Types') + 
    theme(axis.title = element_blank(),
          axis.ticks = element_blank(),
          axis.line = element_blank(),
          axis.text = element_blank(),
          panel.background = element_blank(),
          panel.grid = element_blank(),
          legend.position = 'right',
          legend.key.size = unit(1, 'cm'))
  # Show plot
  if (verbose){
    cat('Plot for PointNum ', point_num, ' completed. \n')
  }
  if (out){
    ggsave(filename = paste0(out_path, plot_title, '.png'), plot = p, device = 'png', height = 9, width = 9, units = 'in', dpi = 320)
    #legend_plot <- cowplot::get_legend(p)
    #ggsave(filename = paste0(out_path, 'legend.pdf'), plot = legend_plot, device = 'pdf', dpi = 320)
  }
  if (print_fig){
    print(p)
  }
}

```


```{r}

library(foreach)

mypalette <- data.frame(celltype = c('Tumor', 'Tumor Proximal', 'Tumor Distal', 'Far'),
                        color = c('#E41A1C', '#393B79', '#5254A3', '#6B6ECF'))

cl <- parallel::makeCluster(20)
doParallel::registerDoParallel(cl)

foreach (i = unique(new_annotation$pointNum)) %dopar% {
  celltype_plot(i, mask_list, new_annotation$score[new_annotation$pointNum == i], new_annotation$cellLabel[new_annotation$pointNum == i], mypalette = mypalette, pointNumLUT = pointNum_ID_region_LUT, verbose = TRUE, out = TRUE, out_path = '~/hodgkinebvmibi/paper_figures/score_map_singleFOV_073123/')
}

parallel::stopCluster(cl)

```



### Figure 4C


```{r}

exhaustion_df <- hodgkin_annotated %>% 
  dplyr::filter(Annotation %in% c('CD4', 'CD8', 'DC', 'M1', 'M2', 'Cytotoxic CD4', 'Cytotoxic CD8', 'Treg'))


exhaustion_df <- exhaustion_df %>% 
  mutate(exhaustion_score_v3 = case_when(Annotation %in% c('CD4', 'CD8', 'Cytotoxic CD4', 'Cytotoxic CD8', 'Treg') ~ CD45RO - CD45RA + Tox + `PD-1` - `Ki-67` + Lag3,
                                         Annotation %in% c('DC', 'M1', 'M2') ~ `PD-L1` - `Ki-67`))

```


```{r}


for (j in unique(exhaustion_df$Annotation)){
  
  celltype_data <- exhaustion_df %>% 
    filter(Annotation == j) %>% 
    filter(bin_deriva != 'Far')
  
  if (nrow(celltype_data) <= 1) {
    next
  } 
  
  summary_data <- celltype_data %>% 
    dplyr::select(pointNum, bin_deriva, ebv_status, exhaustion_score_v3, cellLabel) %>% 
    group_by(pointNum, bin_deriva, ebv_status) %>% 
    summarise(score_avg = mean(exhaustion_score_v3))
  
  

  # p <- summary_data %>%
  # mutate(bin_deriva = factor(bin_deriva, levels = c('Tumor Dense', 'Tumor Sparse'))) %>%
  # ggplot(aes(x = bin_deriva, y = score_avg, fill = ebv_status)) +
  # #geom_violin(position = position_dodge(1), alpha = 0.5) +
  # geom_boxplot(position = position_dodge(1), outlier.alpha = 0) +
  # geom_jitter(position = position_jitterdodge(jitter.width = 0.15, dodge.width = 1)) +
  # #geom_text_repel(data = summary_data, aes(x = bin, y = avg, label = n, color = ebv_status)) +
  # stat_compare_means(aes(group = ebv_status), method = 'wilcox.test', label = 'p.signif', method.args = list(alternative = 'less')) +
  # scale_fill_manual(values = c("#D55E00", "#009E73")) +
  # scale_color_manual(values = c("#D55E00", "#009E73")) +
  # theme_bw() +
  # theme(axis.text = element_text(size = 12),
  #       legend.position = 'none') +
  # labs(y = 'Exhaustion Score', x = 'Bin')
  
  
  p <- summary_data %>%
  mutate(ebv_status = factor(ebv_status, levels = c('Positive', 'Negative'))) %>% 
  mutate(bin_deriva = factor(bin_deriva, levels = c('Tumor Dense', 'Tumor Sparse'))) %>% 
  ungroup() %>% 
  group_by(pointNum) %>% 
  mutate(diff = lag(score_avg) - score_avg) %>% 
  mutate(diff = ifelse(is.na(diff), diff[!is.na(diff)], diff)) %>% 
  mutate(diff_0 = ifelse(diff > 0, 'greater', 'less')) %>% 
  ggplot(aes(x = interaction(bin_deriva, ebv_status), y = score_avg, fill = bin_deriva)) +
  #geom_violin(position = position_dodge(1), alpha = 0.5) +
  geom_boxplot(outlier.alpha = 0) +
  geom_point(alpha = 0.5) +
  geom_line(aes(group = interaction(pointNum, ebv_status), linetype = diff_0, color = diff_0), alpha = 0.3) +
  #geom_text(aes(label = pointNum)) + 
  #geom_text_repel(data = summary_data, aes(x = bin, y = avg, label = n, color = ebv_status)) +
  #stat_compare_means(aes(group = ebv_status), method = 'wilcox.test', label = 'p.signif', method.args = list(alternative = 'less')) +
  scale_fill_manual(values = c('#f6adff', '#e1d936')) +
  scale_color_manual(values = c("#f228a0", "#096013")) +
  theme_bw() +
  theme(axis.text = element_text(size = 12),
        legend.position = 'none',
        axis.text.x = element_text(angle = -30)) +
  labs(y = 'Exhaustion Score', x = 'Bin')

    
    ggsave(filename = paste0('/mnt/nfs/home/huayingqiu/hodgkinebvmibi/paper_figures/figure4/figure4c/', j, '.pdf'), p, width = 5, height = 10, unit = 'cm', dpi = 320)
  
}


```


## Supplementary

### Test heatmap

#### Figure2

```{r}

fig2_test_df <- read_csv('~/hodgkinebvmibi/paper_figures/figure2/test.csv')

fig2_test_df <- fig2_test_df %>% 
  mutate(plot_value = ifelse(reject.adj == 1, p.value, NA))


MHC1_test <- fig2_test_df %>% 
  filter(marker %in% c('B2-Microglobulin', 'HLA1') & 
           celltype %in% c('CD4', 'CD8', 'Cytotoxic CD4', 'Cytotoxic CD8', 'Endothelial', 'Neutrophil', 'NK', 'Treg')) %>% 
  #mutate(marker = paste0(marker, ', EBV+ vs. EBV-')) %>%
  mutate(marker = factor(marker, level = c('HLA1', 'B2-Microglobulin'))) %>% 
  mutate(reject.adj = factor(reject.adj, levels = c(1, 0), labels = c('Significant', 'Non-significant'))) %>%
  ggplot(aes(x = celltype, y = marker, fill = plot_value)) + 
  geom_tile(color = 'black', size = 0.5) +
  scale_fill_gradient(na.value = '#F3F9F1', high = 'white', low = '#C32136', limits = c(0, 0.05), breaks = c(0, 0.01, 0.02, 0.03, 0.04, 0.05)) + 
  #scale_fill_manual(values = c('Significant' = '#C32136', 'Non-significant' = '#F3F9F1'))+
  theme_bw() + 
  labs(fill = 'Test Result', title = 'Difference between marker, EBV+ vs. EBV-') + 
  theme(panel.background = element_blank(),
        panel.grid = element_blank(),
        panel.border = element_blank(),
        axis.ticks = element_blank(),
        axis.title = element_blank(),
        axis.text.x = element_text(angle = 90)) + 
  coord_equal()

ggsave('~/hodgkinebvmibi/paper_figures/figure2/supp/supp_MHC1.pdf', MHC1_test)

MHC2_test <- fig2_test_df %>% 
  filter(marker %in% c('B2-Microglobulin', 'HLA1', 'HLA-DR') & 
           celltype %in% c('B', 'DC', 'M1', 'M2', 'Tumor')) %>% 
  #mutate(marker = paste0(marker, ', EBV+ vs. EBV-')) %>%
  mutate(marker = factor(marker, level = c('HLA-DR', 'HLA1', 'B2-Microglobulin'))) %>% 
  mutate(reject.adj = factor(reject.adj, levels = c(1, 0), labels = c('Significant', 'Non-significant'))) %>%
  ggplot(aes(x = celltype, y = marker, fill = plot_value)) + 
  geom_tile(color = 'black', size = 0.5) +
  scale_fill_gradient(na.value = '#F3F9F1', high = 'white', low = '#C32136', limits = c(0, 0.05), breaks = c(0, 0.01, 0.02, 0.03, 0.04, 0.05)) + 
  #scale_fill_manual(values = c('Significant' = '#C32136', 'Non-significant' = '#F3F9F1'))+
  theme_bw() + 
  labs(fill = 'Test Result', title = 'Difference between marker, EBV+ vs. EBV-') + 
  theme(panel.background = element_blank(),
        panel.grid = element_blank(),
        panel.border = element_blank(),
        axis.ticks = element_blank(),
        axis.title = element_blank(),
        axis.text.x = element_text(angle = 90)) + 
  coord_equal()

ggsave('~/hodgkinebvmibi/paper_figures/figure2/supp/supp_MHC2.pdf', MHC2_test)

exhaustion_t <- fig2_test_df %>% 
  filter(marker %in% c('PD-1', 'Lag3', 'Tox', 'CD45RO')& 
           celltype %in% c('CD4', 'CD8', 'Cytotoxic CD4', 'Cytotoxic CD8', 'Treg')) %>% 
  #mutate(marker = paste0(marker, ', EBV+ vs. EBV-')) %>%
  mutate(marker = factor(marker, level = c('PD-1', 'Lag3', 'Tox', 'CD45RO'))) %>% 
  mutate(reject.adj = factor(reject.adj, levels = c(1, 0), labels = c('Significant', 'Non-significant'))) %>%
  ggplot(aes(x = celltype, y = marker, fill = plot_value)) + 
  geom_tile(color = 'black', size = 0.5) +
  scale_fill_gradient(na.value = '#F3F9F1', high = 'white', low = '#C32136', limits = c(0, 0.05), breaks = c(0, 0.01, 0.02, 0.03, 0.04, 0.05)) + 
  #scale_fill_manual(values = c('Significant' = '#C32136', 'Non-significant' = '#F3F9F1'))+
  theme_bw() + 
  labs(fill = 'Test Result', title = 'Difference between marker, EBV+ vs. EBV-') + 
  theme(panel.background = element_blank(),
        panel.grid = element_blank(),
        panel.border = element_blank(),
        axis.ticks = element_blank(),
        axis.title = element_blank(),
        axis.text.x = element_text(angle = 90)) + 
  coord_equal()

ggsave('~/hodgkinebvmibi/paper_figures/figure2/supp/supp_exhaustion_t.pdf', exhaustion_t)

exhaustion_other <- fig2_test_df %>% 
  filter(marker %in% c('PD-L1')& 
           celltype %in% c('DC', 'M1', 'M2', 'Tumor')) %>% 
  #mutate(marker = paste0(marker, ', EBV+ vs. EBV-')) %>%
  mutate(marker = factor(marker, level = c('PD-L1'))) %>% 
  mutate(reject.adj = factor(reject.adj, levels = c(1, 0), labels = c('Significant', 'Non-significant'))) %>%
  ggplot(aes(x = celltype, y = marker, fill = plot_value)) + 
  geom_tile(color = 'black', size = 0.5) +
  scale_fill_gradient(na.value = '#F3F9F1', high = 'white', low = '#C32136', limits = c(0, 0.05), breaks = c(0, 0.01, 0.02, 0.03, 0.04, 0.05)) + 
  #scale_fill_manual(values = c('Significant' = '#C32136', 'Non-significant' = '#F3F9F1'))+
  theme_bw() + 
  labs(fill = 'Test Result', title = 'Difference between marker, EBV+ vs. EBV-') + 
  theme(panel.background = element_blank(),
        panel.grid = element_blank(),
        panel.border = element_blank(),
        axis.ticks = element_blank(),
        axis.title = element_blank(),
        axis.text.x = element_text(angle = 90)) + 
  coord_equal()

ggsave('~/hodgkinebvmibi/paper_figures/figure2/supp/supp_exhaustion_other.pdf', exhaustion_other)

```

#### Figure 3


```{r}

fig3e_test <- read_csv('~/hodgkinebvmibi/paper_figures/figure3/fig3e_test.csv')

fig3e_test <- fig3e_test %>% 
  mutate(plot_value = ifelse(reject.adj == 1, p.value, NA))

test1 <- fig3e_test %>% 
  mutate(test = str_replace(test, 'Positive', 'EBV+')) %>% 
  mutate(test = str_replace(test, 'Negative', 'EBV-')) %>% 
  filter(str_detect(test, 'EBV\\+')) %>% 
  filter(celltype %in% c('CD4', 'CD8', 'Cytotoxic CD4', 'Cytotoxic CD8', 'Treg') & 
           marker %in% c('PD-1', 'Lag3', 'Tox', 'CD45RO', 'HLA1', 'B2-Microglobulin')) %>% 
  mutate(marker = factor(marker, levels = c('PD-1', 'Lag3', 'Tox', 'CD45RO', 'HLA1', 'B2-Microglobulin'))) %>% 
  ggplot(aes(x = celltype, y = interaction(marker, test, sep = ', '), fill = plot_value)) + 
  geom_tile(color = 'black', size = 0.5) +
  scale_fill_gradient(na.value = '#F3F9F1', high = 'white', low = '#C32136', limits = c(0, 0.05), breaks = c(0, 0.01, 0.02, 0.03, 0.04, 0.05)) + 
  #scale_fill_manual(values = c('Significant' = '#C32136', 'Non-significant' = '#F3F9F1'))+
  theme_bw() + 
  labs(fill = 'Test Result', title = 'Difference between marker within EBV+, CN0 vs. CN1') + 
  theme(panel.background = element_blank(),
        panel.grid = element_blank(),
        panel.border = element_blank(),
        axis.ticks = element_blank(),
        axis.title = element_blank(),
        axis.text.x = element_text(angle = 90)) + 
  coord_equal()

ggsave('~/hodgkinebvmibi/paper_figures/figure3/supp/test1.pdf', test1)

test2 <- fig3e_test %>% 
  mutate(test = str_replace(test, 'Positive', 'EBV+')) %>% 
  mutate(test = str_replace(test, 'Negative', 'EBV-')) %>% 
  filter(str_detect(test, 'EBV\\-')) %>% 
  filter(celltype %in% c('CD4', 'CD8', 'Cytotoxic CD4', 'Cytotoxic CD8', 'Treg') & 
           marker %in% c('PD-1', 'Lag3', 'Tox', 'CD45RO', 'HLA1', 'B2-Microglobulin')) %>% 
  mutate(marker = factor(marker, levels = c('PD-1', 'Lag3', 'Tox', 'CD45RO', 'HLA1', 'B2-Microglobulin'))) %>% 
  ggplot(aes(x = celltype, y = interaction(marker, test, sep = ', '), fill = plot_value)) + 
  geom_tile(color = 'black', size = 0.5) +
  scale_fill_gradient(na.value = '#F3F9F1', high = 'white', low = '#C32136', limits = c(0, 0.05), breaks = c(0, 0.01, 0.02, 0.03, 0.04, 0.05)) + 
  #scale_fill_manual(values = c('Significant' = '#C32136', 'Non-significant' = '#F3F9F1'))+
  theme_bw() + 
  labs(fill = 'Test Result', title = 'Difference between marker within EBV-, CN0 vs. CN1') + 
  theme(panel.background = element_blank(),
        panel.grid = element_blank(),
        panel.border = element_blank(),
        axis.ticks = element_blank(),
        axis.title = element_blank(),
        axis.text.x = element_text(angle = 90)) + 
  coord_equal()

ggsave('~/hodgkinebvmibi/paper_figures/figure3/supp/test2.pdf', test2)

test3 <- fig3e_test %>% 
  mutate(test = str_replace(test, 'Positive', 'EBV+')) %>% 
  mutate(test = str_replace(test, 'Negative', 'EBV-')) %>% 
  filter(str_detect(test, 'EBV\\+')) %>% 
  filter(celltype %in% c('DC', 'M1', 'M2', 'Tumor') & 
           marker %in% c('PD-L1', 'HLA-DR', 'HLA1', 'B2-Microglobulin')) %>% 
  mutate(marker = factor(marker, levels = c('PD-L1', 'HLA-DR', 'HLA1', 'B2-Microglobulin'))) %>% 
  ggplot(aes(x = celltype, y = interaction(marker, test, sep = ', '), fill = plot_value)) + 
  geom_tile(color = 'black', size = 0.5) +
  scale_fill_gradient(na.value = '#F3F9F1', high = 'white', low = '#C32136', limits = c(0, 0.05), breaks = c(0, 0.01, 0.02, 0.03, 0.04, 0.05)) + 
  #scale_fill_manual(values = c('Significant' = '#C32136', 'Non-significant' = '#F3F9F1'))+
  theme_bw() + 
  labs(fill = 'Test Result', title = 'Difference between marker within EBV+, CN0 vs. CN1') + 
  theme(panel.background = element_blank(),
        panel.grid = element_blank(),
        panel.border = element_blank(),
        axis.ticks = element_blank(),
        axis.title = element_blank(),
        axis.text.x = element_text(angle = 90)) + 
  coord_equal()

ggsave('~/hodgkinebvmibi/paper_figures/figure3/supp/test3.pdf', test3)

test4 <- fig3e_test %>% 
  mutate(test = str_replace(test, 'Positive', 'EBV+')) %>% 
  mutate(test = str_replace(test, 'Negative', 'EBV-')) %>% 
  filter(str_detect(test, 'EBV\\-')) %>% 
  filter(celltype %in% c('DC', 'M1', 'M2', 'Tumor') & 
           marker %in% c('PD-L1', 'HLA-DR', 'HLA1', 'B2-Microglobulin')) %>% 
  mutate(marker = factor(marker, levels = c('PD-L1', 'HLA-DR', 'HLA1', 'B2-Microglobulin'))) %>% 
  ggplot(aes(x = celltype, y = interaction(marker, test, sep = ', '), fill = plot_value)) + 
  geom_tile(color = 'black', size = 0.5) +
  scale_fill_gradient(na.value = '#F3F9F1', high = 'white', low = '#C32136', limits = c(0, 0.05), breaks = c(0, 0.01, 0.02, 0.03, 0.04, 0.05)) + 
  #scale_fill_manual(values = c('Significant' = '#C32136', 'Non-significant' = '#F3F9F1'))+
  theme_bw() + 
  labs(fill = 'Test Result', title = 'Difference between marker within EBV-, CN0 vs. CN1') + 
  theme(panel.background = element_blank(),
        panel.grid = element_blank(),
        panel.border = element_blank(),
        axis.ticks = element_blank(),
        axis.title = element_blank(),
        axis.text.x = element_text(angle = 90)) + 
  coord_equal()

ggsave('~/hodgkinebvmibi/paper_figures/figure3/supp/test4.pdf', test4)
  

```


```{r}

exhaustion_test_df <- read_csv('~/hodgkinebvmibi/paper_figures/figure4/fig4c_test.csv')

exhaustion_test_result_df %>% 
  mutate(ebv_status = paste0('Dense vs. Sparse, ', str_extract(test, '(?<=, ).*'))) %>% 
  mutate(reject.adj = factor(reject.adj, levels = c(1, 0), labels = c('Significant', 'Non-significant'))) %>% 
  ggplot(aes(x = celltype, y = ebv_status, fill = reject.adj)) + 
  geom_tile(color = 'black', size = 0.5) +
  scale_fill_manual(values = c('Significant' = '#C32136', 'Non-significant' = '#F3F9F1'))+
  theme_bw() + 
  labs(fill = 'Test Result', title = 'Difference between the exhaustion score of tumor dense and sparse area') + 
  theme(panel.background = element_blank(),
        panel.grid = element_blank(),
        panel.border = element_blank(),
        axis.ticks = element_blank(),
        axis.title = element_blank(),
        axis.text.x = element_text(angle = 90))

```

#### Figure 4

```{r}

exhaustion_supp <- exhaustion_df %>% 
  filter(bin_deriva != 'Far') %>% 
  dplyr::select(pointNum, Annotation, ebv_status, bin_deriva, CD45RO, CD45RA, Tox, `PD-1`, `Ki-67`, Lag3, `PD-L1`) %>% 
  pivot_longer(cols = -c(pointNum, Annotation, ebv_status, bin_deriva), names_to = 'marker', values_to = 'value') %>% 
  group_by(pointNum, Annotation, ebv_status, bin_deriva, marker) %>% 
  summarise(mu = mean(value)) %>% 
  ggplot(aes(x = interaction(bin_deriva, ebv_status), y = mu, fill = bin_deriva)) + 
  geom_boxplot(position = position_dodge(1), outlier.alpha = 0) + 
  geom_point(position = position_jitterdodge(), alpha = 0.5) + 
  coord_cartesian(ylim = c(0,1)) + 
  stat_compare_means(comparisons = list(c('Tumor Dense.Positive', 'Tumor Sparse.Positive'), c('Tumor Dense.Negative', 'Tumor Sparse.Negative')), 
                     method.args = list(alternative = 'greater', exact = FALSE),
                     label = 'p.signif', label.y = 0.9) + 
  facet_grid(vars(Annotation), vars(marker), scales = 'free_y') + 
  scale_fill_manual(values = c('#f6adff', '#e1d936')) + 
  theme_bw() + 
  theme(axis.text.x = element_blank(),
        axis.ticks.x = element_blank(),
        legend.position = 'none') + 
  labs(x = 'Tumor Density, EBV Status', y = 'Mean Marker Expression', fill = 'Tumor Density')

ggsave('~/hodgkinebvmibi/paper_figures/figure4/supp/individual_marker.pdf', exhaustion_supp, height = 15, width = 10, units = 'cm')

```











